# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).

{ config, lib, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ../../modules/caches.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 5;
  boot.loader.efi.canTouchEfiVariables = true;
  networking.hostName = "antec-pc";
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Australia/Sydney";

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";
  # console = {
  #   font = "Lat2-Terminus16";
  #   keyMap = "us";
  #   useXkbConfig = true; # use xkb.options in tty.
  # };

  # Enable the X11 windowing system.
  services = {
    xserver.enable = true;
    displayManager.sddm.enable = true;
    desktopManager.plasma6.enable = true;
  };
  

  # Configure keymap in X11
  # services.xserver.xkb.layout = "us";
  # services.xserver.xkb.options = "eurosign:e,caps:escape";

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable sound.
  # services.pulseaudio.enable = true;
  # OR
  #security.rtkit.enable = true;
  #services.pipewire = {
  #  enable = true;
  #  pulse.enable = true;
  #  alsa.enable = true;
  #  alsa.support32Bit = true;
  #  jack.enable = true;
  #};

  # Enable touchpad support (enabled default in most desktopManager).
  # services.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.miltu = {
    isNormalUser = true;
    home = "/home/miltu";
    extraGroups = [ "wheel" "hermes" ];
    packages = with pkgs; [
      tree
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBo/KF7ZUTO6Nkai8cKwWMsU78sxVrFXwjcZ/fxm9Ksp antec-admin"
    ];
  };

  # Extend the service account created by the upstream Hermes module. Rootless
  # Podman maps additional container users to an unprivileged ID range.
  users.users.hermes.autoSubUidGidRange = true;

  # Decrypt the existing reusable raw key for the dedicated Hermes account.
  # System-level Agenix is separate from Home Manager's Agenix instance.
  age.identityPaths = [ "/home/miltu/.config/age/master.key" ];
  age.secrets.hermes-deepseek-api-key = {
    file = ../../secrets/deepseek-api-key.age;
    owner = "hermes";
    group = "hermes";
    mode = "0400";
  };
  age.secrets.hermes-telegram-bot-token = {
    file = ../../secrets/telegram-bot-token.age;
    owner = "hermes";
    group = "hermes";
    mode = "0400";
  };

  # Hermes invokes Podman directly as its non-root service account.
  virtualisation.podman.enable = true;

  services.hermes-agent = {
    enable = true;

    settings = {
      # Use DeepSeek V4 Pro through direct DEEPSEEK_API_KEY access.
      model = "deepseek-v4-pro";

      terminal = {
        # Upstream defaults to local host execution. Use the Docker-compatible
        # sandbox implementation and select Podman through HERMES_DOCKER_BINARY.
        backend = "docker";

        # Expose only the dedicated persistent workspace to generated commands.
        docker_volumes = [
          "/var/lib/hermes/workspace:/workspace"
        ];

        # Keep accidental cwd mounts and credential forwarding disabled.
        docker_mount_cwd_to_workspace = false;
        docker_forward_env = [];

        # Bound sandbox usage for this machine. Upstream defaults are 5120 MB
        # memory and 51200 MB disk.
        container_memory = 2048;
        container_disk = 10240;
      };

      # Keep third-party gateway plugins disabled until explicitly reviewed.
      plugins.enabled = [];
    };
  };

  # The upstream environmentFiles option expects complete KEY=value fragments.
  # Compose Hermes' private dotenv file from reusable raw secrets after Agenix
  # decrypts them during system activation.
  system.activationScripts.hermes-agent-compose-env = {
    deps = [
      "agenix"
      "hermes-agent-setup"
    ];
    text = ''
      set -eu
      umask 077
      env_file=/var/lib/hermes/.hermes/.env
      deepseek_secret_file=${config.age.secrets.hermes-deepseek-api-key.path}
      telegram_secret_file=${config.age.secrets.hermes-telegram-bot-token.path}

      test -r "$deepseek_secret_file"
      test -r "$telegram_secret_file"
      : > "$env_file"
      chmod 0600 "$env_file"
      printf 'DEEPSEEK_API_KEY=%s\n' "$(cat "$deepseek_secret_file")" >> "$env_file"
      printf 'TELEGRAM_BOT_TOKEN=%s\n' "$(cat "$telegram_secret_file")" >> "$env_file"
    '';
  };

  # Merge local hardening into the unit generated by the upstream Hermes module.
  systemd.services.hermes-agent = {
    environment = {
      # The upstream Docker-compatible terminal backend supports Podman directly.
      HERMES_DOCKER_BINARY = lib.getExe config.virtualisation.podman.package;
      # Python dependencies must be declared in the immutable Nix package.
      HERMES_DISABLE_LAZY_INSTALLS = "1";
    };

    # Restart Hermes after a declared key change so it reloads the composed
    # dotenv file. Unrelated rebuilds do not restart the service.
    restartTriggers = [
      config.age.secrets.hermes-deepseek-api-key.file
      config.age.secrets.hermes-telegram-bot-token.file
    ];

    serviceConfig = {
      # Pin the desired upstream hardening defaults explicitly.
      NoNewPrivileges = lib.mkForce true;
      ProtectSystem = lib.mkForce "strict";
      PrivateTmp = lib.mkForce true;
      UMask = lib.mkForce "0007";
      ReadWritePaths = lib.mkForce [
        "/var/lib/hermes"
        "/var/lib/hermes/workspace"
      ];

      # Upstream permits home access for optional state sharing. This service
      # does not need /home, /root, or /run/user.
      ProtectHome = lib.mkForce true;

      # Prevent runtime plugin modification. Nix activation can still install
      # reviewed declarative plugins before the service starts.
      ReadOnlyPaths = [
        "/var/lib/hermes/.hermes/plugins"
      ];
    };
  };

  programs.firefox.enable = true;
  programs.fish.enable = true; # Enable system package completions
  programs.zsh.enable = true; # Enable system package completions

  environment.sessionVariables = {
    EDITOR = "hx";
    VISUAL = "hx";
  };

  # Nvidia Proprietary Drivers
  services.xserver.videoDrivers = [ "nvidia" ]; #enables nvidia
  nixpkgs.config.allowUnfree = true;
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.trusted-users = [ "root" "miltu" ];
  nixpkgs.config.nvidia.acceptLicense = true;
  hardware = {
    graphics.enable = true; #seems optional - maybe set somewhere else
    nvidia.modesetting.enable = true; #needed for high res
    # Last version that supports Kepler GPUs
    nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_470;
    # nvidia.open = false; - only applies to drivers >= 560
    nvidia.nvidiaSettings = true;
    # nvidia.forceFullCompositionPipeline = true;
  };
  
  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    helix
    kitty
    ghostty
    (writeShellScriptBin "hermes-service" ''
      cd /var/lib/hermes/workspace
      exec ${util-linux}/bin/runuser --user hermes -- \
        ${coreutils}/bin/env -i \
          HOME=/var/lib/hermes \
          HERMES_HOME=/var/lib/hermes/.hermes \
          HERMES_DOCKER_BINARY=${lib.getExe podman} \
          HERMES_DISABLE_LAZY_INSTALLS=1 \
          PATH=/run/current-system/sw/bin \
          TERM="''${TERM:-xterm-256color}" \
          ${config.services.hermes-agent.package}/bin/hermes "$@"
    '')
    google-chrome
    # debugging utils
    xrandr
    inxi
    pciutils
    virtualgl
    fbset
    hwinfo
  ];

  programs.git = {
    enable = true;
    config = {
      user = {
        name = "Smarak Nayak";
        email = "miltu.s.nayak@gmail.com";
      };
      init.defaultBranch = "main";
    };
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
    };
  };
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish.enable = true;
    publish.addresses = true;
  };

  networking.firewall.allowedTCPPorts = [ 22 ];

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.05"; # Did you read the comment?

}
