{ config, lib, pkgs, ... }:

let
  # The `messaging` extra (python-telegram-bot, discord.py, slack) was dropped
  # from upstream's `[all]` on 2026-05-12 and routed to runtime lazy-install.
  # Lazy installs are disabled here, so bake those deps into the sealed venv.
  # Both the gateway service and the interactive hermes-service wrapper must
  # share this exact package, or the wrapper's send_message tool fails with
  # "python-telegram-bot not installed".
  hermesAgent = pkgs.hermes-agent.override {
    extraDependencyGroups = [ "messaging" ];
  };
in

{
  imports = [
    ./hermes-github-app.nix
  ];

  # Extend the service account created by the upstream Hermes module. Rootless
  # Podman maps additional container users to an unprivileged ID range.
  users.users.hermes.autoSubUidGidRange = true;

  # Decrypt the existing reusable raw key for the dedicated Hermes account.
  # System-level Agenix is separate from Home Manager's Agenix instance.
  age.identityPaths = [ "/home/miltu/.config/age/master.key" ];
  age.secrets.hermes-deepseek-api-key = {
    file = ../../secrets/deepseek-api-key.age;
    owner = "hermes";
    group = "hermes";
    mode = "0400";
  };
  age.secrets.hermes-telegram-bot-token = {
    file = ../../secrets/telegram-bot-token.age;
    owner = "hermes";
    group = "hermes";
    mode = "0400";
  };
  age.secrets.hermes-telegram-chat-id = {
    file = ../../secrets/telegram-chat-id.age;
    owner = "hermes";
    group = "hermes";
    mode = "0400";
  };
  # Hermes invokes Podman directly as its non-root service account.
  virtualisation.podman.enable = true;

  services.hermes-agent = {
    enable = true;

    # Shared messaging-enabled package (see hermesAgent in the let block).
    package = hermesAgent;

    # Browser tools run from the host-side gateway, outside the terminal
    # sandbox. Use Nixpkgs packages instead of runtime npm/browser downloads.
    extraPackages = [
      pkgs.agent-browser
      pkgs.chromium
    ];

    settings = {
      # Use DeepSeek V4 Pro through direct DEEPSEEK_API_KEY access.
      model = "deepseek-v4-pro";

      terminal = {
        # Upstream defaults to local host execution. Use the Docker-compatible
        # sandbox implementation and select Podman through HERMES_DOCKER_BINARY.
        backend = "docker";

        # The host workspace is mounted at /workspace inside the sandbox.
        # Override the module's host-side working directory before Hermes
        # bridges it into TERMINAL_CWD for container startup.
        cwd = "/workspace";

        # Expose only the dedicated persistent workspace to generated commands.
        docker_volumes = [
          "/var/lib/hermes/workspace:/workspace"
        ];

        # Give generated commands a Nix-enabled base environment.
        docker_image = "nixos/nix";

        # Keep accidental cwd mounts and credential forwarding disabled.
        docker_mount_cwd_to_workspace = false;
        docker_forward_env = [];

        # Bound sandbox usage for this machine. Upstream defaults are 5120 MB
        # memory and 51200 MB disk.
        container_memory = 2048;
        container_disk = 10240;
      };

      # Keep third-party gateway plugins disabled until explicitly reviewed.
      plugins.enabled = [];
    };
  };

  # The upstream environmentFiles option expects complete KEY=value fragments.
  # Compose Hermes' private dotenv file from reusable raw secrets after Agenix
  # decrypts them during system activation.
  system.activationScripts.hermes-agent-compose-env = {
    deps = [
      "agenix"
      "hermes-agent-setup"
    ];
    text = ''
      set -eu
      umask 077
      env_file=/var/lib/hermes/.hermes/.env
      deepseek_secret_file=${config.age.secrets.hermes-deepseek-api-key.path}
      telegram_secret_file=${config.age.secrets.hermes-telegram-bot-token.path}
      telegram_chat_id_file=${config.age.secrets.hermes-telegram-chat-id.path}

      test -r "$deepseek_secret_file"
      test -r "$telegram_secret_file"
      test -r "$telegram_chat_id_file"
      : > "$env_file"
      chmod 0600 "$env_file"
      printf 'DEEPSEEK_API_KEY=%s\n' "$(cat "$deepseek_secret_file")" >> "$env_file"
      printf 'TELEGRAM_BOT_TOKEN=%s\n' "$(cat "$telegram_secret_file")" >> "$env_file"
      # The Telegram chat Hermes treats as its home channel doubles as the
      # allowlist of users permitted to talk to the bot. For a private chat the
      # user ID and chat ID are identical, so one secret feeds both.
      telegram_chat_id="$(cat "$telegram_chat_id_file")"
      printf 'TELEGRAM_HOME_CHANNEL=%s\n' "$telegram_chat_id" >> "$env_file"
      printf 'TELEGRAM_ALLOWED_USERS=%s\n' "$telegram_chat_id" >> "$env_file"
    '';
  };

  # Merge local hardening into the unit generated by the upstream Hermes module.
  systemd.services.hermes-agent = {
    environment = {
      # The upstream Docker-compatible terminal backend supports Podman directly.
      HERMES_DOCKER_BINARY = lib.getExe config.virtualisation.podman.package;
      # Python dependencies must be declared in the immutable Nix package.
      HERMES_DISABLE_LAZY_INSTALLS = "1";
      AGENT_BROWSER_EXECUTABLE_PATH = lib.getExe pkgs.chromium;
    };

    # Rootless Podman locates newuidmap/newgidmap via PATH. The module's PATH is
    # Nix-store-only, so the setuid wrappers in /run/wrappers/bin must be added
    # explicitly (listed first so the setuid copies win over any plain ones).
    path = [ "/run/wrappers" "/run/current-system/sw" ];

    # Restart Hermes after a declared key change so it reloads the composed
    # dotenv file. Unrelated rebuilds do not restart the service.
    restartTriggers = [
      config.age.secrets.hermes-deepseek-api-key.file
      config.age.secrets.hermes-telegram-bot-token.file
      config.age.secrets.hermes-telegram-chat-id.file
    ];

    serviceConfig = {
      # Rootless Podman must run the setuid newuidmap/newgidmap helpers to map
      # its subuid range. NoNewPrivileges blocks setuid, so the gateway cannot
      # cold-init its namespace with it enabled. Allowing it here lets Podman
      # initialize directly - far simpler than a pre-warming init service. The
      # remaining hardening below still confines the unprivileged hermes account.
      NoNewPrivileges = lib.mkForce false;
      ProtectSystem = lib.mkForce "strict";
      PrivateTmp = lib.mkForce true;
      UMask = lib.mkForce "0007";
      ReadWritePaths = lib.mkForce [
        "/var/lib/hermes"
        "/var/lib/hermes/workspace"
      ];

      # Upstream permits home access for optional state sharing. This service
      # does not need /home, /root, or /run/user.
      ProtectHome = lib.mkForce true;

      # Prevent runtime plugin modification. Nix activation can still install
      # reviewed declarative plugins before the service starts.
      ReadOnlyPaths = [
        "/var/lib/hermes/.hermes/plugins"
      ];
    };
  };

  environment.systemPackages = [
    (pkgs.writeShellScriptBin "hermes-service" ''
      cd /var/lib/hermes/workspace
      exec ${pkgs.util-linux}/bin/runuser --user hermes -- \
        ${pkgs.coreutils}/bin/env -i \
          HOME=/var/lib/hermes \
          HERMES_HOME=/var/lib/hermes/.hermes \
          HERMES_DOCKER_BINARY=${lib.getExe config.virtualisation.podman.package} \
          HERMES_DISABLE_LAZY_INSTALLS=1 \
          AGENT_BROWSER_EXECUTABLE_PATH=${lib.getExe pkgs.chromium} \
          PATH=/run/wrappers/bin:/run/current-system/sw/bin:${lib.makeBinPath [ pkgs.agent-browser pkgs.chromium ]} \
          TERM="''${TERM:-xterm-256color}" \
          ${hermesAgent}/bin/hermes "$@"
    '')
  ];
}
